default:
  image:
    name: amazon/aws-cli
    entrypoint: [""]

variables:
  DEPLOY_BRANCH: "main"

before_script:
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install terraform
  - aws --version
  - cd iac

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - iac/.terraform/
    - iac/.terraform.lock.hcl
  policy: pull-push

stages:
  - plan
  - apply

plan:prod:
  stage: plan
  environment:
    name: Production
  script:
    - |
      terraform init
      terraform plan \
        -var-file="environment/prod-terraform.tfvars" \
        -var "account_id=$ACCOUNT_ID"
  rules:
    - if: $CI_COMMIT_BRANCH

apply:prod:
  stage: apply
  environment:
    name: Production
  script:
    - |
      terraform init
      terraform apply \
        -var-file="environment/prod-terraform.tfvars" \
        -var "account_id=$ACCOUNT_ID" -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH == $DEPLOY_BRANCH'
      when: manual